MVCRomjanProject/MyProject/MVCAvedianceExam/MVCAvedianceExam/Controllers/ProductsController.cs
using MVCAvedianceExam.Models;
using MVCAvedianceExam.Models.ViewModels;
using MVCAvedianceExam.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAvedianceExam.Controllers
{
    public class ProductsController : Controller
    {
        ProductRepository repo = new ProductRepository();
        [HttpGet]
        public ActionResult Index(string SearchString, string CurrentFilter, string SortOrder, int? page)
        {
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewBag.SortNameParam = string.IsNullOrEmpty(SortOrder) ? "name_desc" : "";
            ViewBag.CurrentFilter = SearchString;
            IEnumerable<ProductViewModel> list = repo.GetAllProduct();
            if (!string.IsNullOrEmpty(SearchString))
            {
                list = list.Where(e => e.ProductName.ToUpper().Contains(SearchString.ToUpper())).ToList();
            }
            switch (SortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(e => e.ProductName).ToList();
                    break;
                default:
                    list = list.OrderBy(e => e.ProductName).ToList();
                    break;

            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ViewResult Create()
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            return View();
        }
        [HttpGet]
        public ViewResult Edit(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product productObj = repo.GetProductById(id);
            ProductViewModel obj = new ProductViewModel();
            obj.ProductId = productObj.ProductId;
            obj.ProductName = productObj.ProductName;
            obj.PurchaseDate = productObj.PurchaseDate;
            obj.SupplierId = productObj.SupplierId;
            obj.Email = productObj.Email;
            obj.Quantity = productObj.Quantity;
            obj.UnitPrice = productObj.UnitPrice;
            obj.ImageName = productObj.ImageName;
            obj.ImageUrl = productObj.ImageUrl;
            return View(obj);
        }
        [HttpPost]
        [ActionName("Create")]
        public ActionResult PostCreate(ProductViewModel obj)
        {
            var result = false;
            Product obj1;
            if (obj.ProductId == 0)
            {
                if (ModelState.IsValid)
                {
                    obj1 = new Product();
                    obj1.ProductName = obj.ProductName;
                    obj1.PurchaseDate = obj.PurchaseDate;
                    obj1.SupplierId = obj.SupplierId;
                    obj1.Email = obj.Email;
                    obj1.Quantity = obj.Quantity;
                    obj1.UnitPrice = obj.UnitPrice;
                    string fileName = Path.GetFileNameWithoutExtension(obj.ImageFile.FileName);
                    string extension = Path.GetExtension(obj.ImageFile.FileName);
                    obj1.ImageName = fileName + extension;
                    obj1.ImageUrl = "~/Images/" + obj1.ImageName;
                    fileName = Path.Combine(Server.MapPath(obj1.ImageUrl));
                    obj.ImageFile.SaveAs(fileName);
                    repo.SaveProduct(obj1);
                    result = true;

                }
            }
            else
            {
                obj1 = repo.GetProductById(obj.ProductId);
                obj1.ProductName = obj.ProductName;
                obj1.PurchaseDate = obj.PurchaseDate;
                obj1.SupplierId = obj.SupplierId;
                obj1.Email = obj.Email;
                obj1.Quantity = obj.Quantity;
                obj1.UnitPrice = obj.UnitPrice;
                if (obj.ImageFile != null)
                {
                    DeleteExistingImage(obj1.ImageName);
                    string fileName = Path.GetFileNameWithoutExtension(obj.ImageFile.FileName);
                    string extension = Path.GetExtension(obj.ImageFile.FileName);
                    obj1.ImageName = fileName + extension;
                    obj1.ImageUrl = "~/Images/" + obj1.ImageName;
                    fileName = Path.Combine(Server.MapPath(obj1.ImageUrl));
                    obj.ImageFile.SaveAs(fileName);
                }
                else
                {
                    obj.ImageName = obj1.ImageName;
                    obj.ImageUrl = obj1.ImageUrl;
                }
                repo.UpdateProduct(obj1);
                result = true;
            }
            if (result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                List<Supplier> list = repo.GetSuppliers();
                ViewBag.Suppliers = list;
                return View();
            }
        }


        private void DeleteExistingImage(string imagename)
        {
            string root = Server.MapPath("~");
            string parent = Path.GetDirectoryName(root);
            string path = parent + "/Images/" + imagename;
            FileInfo fileObj = new FileInfo(path);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }
        [HttpGet]
        public ViewResult Delete(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product product = repo.GetProductById(id);
            ProductViewModel obj = new ProductViewModel();
            obj.ProductId = product.ProductId;
            obj.ProductName = product.ProductName;
            obj.PurchaseDate = product.PurchaseDate;
            obj.SupplierId = product.SupplierId;
            obj.SupplierName = product.Supplier.SupplierName;
            obj.Email = product.Email;
            obj.Quantity = product.Quantity;
            obj.UnitPrice = product.UnitPrice;
            obj.ImageName = product.ImageName;
            obj.ImageUrl = product.ImageUrl;
            return View(obj);
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult PostDelete(ProductViewModel viewObj)
        {
            Product obj = repo.GetProductById(viewObj.ProductId);
            string imageName = viewObj.ImageName;
            DeleteExistingImage(imageName);
            repo.DeleteProduct(obj.ProductId);
            return RedirectToAction("Index");
        }
        public PartialViewResult Details(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product product = repo.GetProductById(id);
            ProductViewModel obj = new ProductViewModel();
            obj.ProductId = product.ProductId;
            obj.ProductName = product.ProductName;
            obj.PurchaseDate = product.PurchaseDate;
            obj.SupplierId = product.SupplierId;
            obj.SupplierName = product.Supplier.SupplierName;
            obj.Email = product.Email;
            obj.Quantity = product.Quantity;
            obj.UnitPrice = product.UnitPrice;
            obj.ImageName = product.ImageName;
            obj.ImageUrl = product.ImageUrl;
            ViewBag.Details = "Show";
            return PartialView("_DetailsRecord", obj);
        }
    }
}

MVCRomjanProject/MyProject/MVCAvedianceExam/MVCAvedianceExam/Controllers/SuppliersController.cs
using MVCAvedianceExam.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAvedianceExam.Controllers
{
    public class SuppliersController : Controller
    {
        EcommerceDBEntities dbObj = new EcommerceDBEntities();
        // GET: Suppliers
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateSupplier()
        {
            var Model = dbObj.Suppliers.ToList();
            return View(Model);
        }
        public ActionResult AjaxCreateSupplier(Supplier obj)
        {
            if (ModelState.IsValid == true)
            {
                System.Threading.Thread.Sleep(1000);
                dbObj.Suppliers.Add(obj);
                dbObj.SaveChanges();
            }
            IEnumerable<Supplier> Modal = dbObj.Suppliers.ToList();
            return PartialView("_SupplierDetails", Modal);
        }
    }
}

MVCRomjanProject/MyProject/MVCAvedianceExam/MVCAvedianceExam/Views/Shared/_DetailsRecord.cshtml
@model MVCAvedianceExam.Models.ViewModels.ProductViewModel
<div class="col-md-12 mx-auto">
    <h2>Details Product</h2>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.SupplierId, htmlAttributes: new { @class = "form-label" })
        @Html.DropDownListFor(model => model.SupplierId, new SelectList(ViewBag.Suppliers, "SupplierId", "SupplierName"), "Select Supplier", new { @class = "form-select", @disabled = "disabled" })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "form-label  mb-3" })<br />
        <img src="@Url.Content(Model.ImageUrl)" alt="@Model.ImageName" height="120" width="110" class="changeEdit" />
    </div>
</div>

MVCRomjanProject/MyProject/MVCAvedianceExam/MVCAvedianceExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Zupree</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Products", new { area = "" }, new { @class = "nav-link active" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Add New Product", "Create", "Products", new { area = "" }, new { @class = "nav-link active" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Create Supplier", "CreateSupplier", "Suppliers", new { area = "" }, new { @class = "nav-link active" })
                    </li>
                </ul>
                <form class="d-flex">
                    @using (Html.BeginForm("Index", "Products", FormMethod.Get))
                    {
                        @Html.TextBox("SearchString", null, htmlAttributes: new { @class = "form-control me-2", @type = "search", @placeholder = "Search" })
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    }
                </form>
            </div>
        </div>
    </nav>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/Custom.js"></script>
</body>
</html>

MVCRomjanProject/MyProject/MVCAvedianceExam/MVCAvedianceExam/Views/Shared/_SupplierDetails.cshtml
@model IEnumerable<MVCAvedianceExam.Models.Supplier>
<h2>Supplier List</h2>
<div>
    <table class="table table-bordered table-striped">
        <tr>
            <td colspan="2"><h6 class="text-danger">Page Loading @@ : @DateTime.Now.ToString()</h6></td>
        </tr>
        <tr>
            <th>Supplier Id</th>
            <th>Supplier Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.SupplierId</td>
                <td>@item.SupplierName</td>
            </tr>
        }
    </table>
</div>